WebApplication1/Controllers/HomeController.cs
using Business;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class HomeController : baseController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Test()
        {
            var model = new MyTestModel();

            bind(model);

            model.Text4 = DateTime.Today;

            return View(model);
        }

        [AuthorizeUserAttribute]
        [HttpPost]
        public ActionResult Test(MyTestModel model)
        {
            if (!ModelState.IsValid)
            {
                //return Index();
                bind(model);
                return View(model);
            }

            bind(model);

            if (model.File != null)
            {
                var httpPath2 = HttpContext.Server.MapPath("~/Files");
                if (!Directory.Exists(httpPath2))
                {
                    Directory.CreateDirectory(httpPath2);
                }

                //var fileName = Path.GetFileName(file.FileName);
                var pathFileName = Path.Combine(httpPath2, model.File.FileName);
                if (System.IO.File.Exists(pathFileName))
                {
                    System.IO.File.Delete(pathFileName);
                }
                model.File.SaveAs(pathFileName);
            }


            if (model.File != null)
            {
                byte[] uploadedFile = new byte[model.File.InputStream.Length];
                model.File.InputStream.Read(uploadedFile, 0, uploadedFile.Length);
            }

            var httpPath = HttpContext.Server.MapPath("~/Files");
            if (!Directory.Exists(httpPath))
            {
                Directory.CreateDirectory(httpPath); //路徑不存在自已建立
            }

            foreach (HttpPostedFileBase file in model.Files)
            {
                if (file != null)
                {
                    //var fileName = Path.GetFileName(file.FileName);
                    var pathFileName = Path.Combine(httpPath, file.FileName);
                    file.SaveAs(pathFileName);
                }
            }

            //return Content("Thanks for uploading the file");
            return View(model);
        }

        void bind(MyTestModel model)
        {
            model.Select1 = StudentBiz.GetAll().Select(s => new SelectListItem
            {
                Value = s.Sn.ToString(),
                Text = s.Name
            });

            model.Select2 = StudentBiz.GetAll().Select(s => new SelectListItem
            {
                Value = s.Sn.ToString(),
                Text = s.Name
            });

            //班級
            model.ClassSelect = ClassMBiz.GetAll().Select(s => new SelectListItem
            {
                Value = s.Id.ToString(),
                Text = s.Name
            });

            if (!string.IsNullOrWhiteSpace(model.ClassId))
            {
                var list = StudentBiz.ClassData(model.ClassId).Select(s => new SelectListItem
                {
                    Value = s.Sn.ToString(),
                    Text = s.Name
                });

                model.StudentSelect = list;
            }
            else
            {
                model.StudentSelect = new List<SelectListItem>();
            }
        }

        public ActionResult ClassStud(string id)
        {
            //var defItem = new SelectListItem { Text = "請選擇", Value = "" };

            var list = StudentBiz.ClassData(id).Select(s => new SelectListItem
            {
                Value = s.Sn.ToString(),
                Text = s.Name
            }).ToList();

            //list.Insert(0, defItem);

            return Json(list, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Login()
        {
            //Logout();
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginModels User, string returnUrl)
        {
            if (this.ModelState.IsValid)
            {
                //SysUserMInfo info = SysUserMBiz.GetInfo(User.UserId);
                if (!string.IsNullOrWhiteSpace(User.UserId) && User.Pwd == User.Pwd)
                {
                    SessionModels sessionModel = new SessionModels();
                    sessionModel.UserId = User.UserId;

                    HttpContext.Session[AuthorizeUserAttribute.SessionId] = sessionModel;

                    if (string.IsNullOrWhiteSpace(returnUrl))
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        if (Url.IsLocalUrl(returnUrl))
                        {
                            return Redirect(returnUrl);
                        }
                        else
                        {
                            return RedirectToAction("Index", "Home");
                        }
                    }
                }
            }
            return View();
        }
    }
}

WebApplication1/Controllers/StudentBaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Business;
using Information;
using System.IO;
namespace WebApplication1.Controllers
{
    public partial class StudentBaseController : Controller
    {
        public ActionResult Index(int? page)
        {
            StudentListModel model = new StudentListModel();

            var list = StudentBiz.GetAll();

            int currentPageIndex = page.HasValue ? page.Value - 1 : 0;
            int pageSize = 2;
            while (currentPageIndex > 0 &&
                list.Count <= currentPageIndex * pageSize)
            {
                currentPageIndex--;
            }

            model.List = new MvcPaging.PagedList<StudentInfo>(list, currentPageIndex, pageSize);

            bindList(model);

            return View(model);
        }

        public ActionResult Details(int? Sn)
        {
            if (Sn != null)
            {
                StudentModel model = new StudentModel();
                model.Info = StudentBiz.GetInfo((int)Sn);
                return View(model);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Create()
        {
            StudentModel model = new StudentModel();
            bindEdit(model);
            return View("Edit", model);
        }

        [HttpPost]
        public ActionResult Create(StudentModel model)
        {
            if (!ModelState.IsValid)
            {
                bindEdit(model);
                return View("Edit", model);
            }
            if (model.PhotoFile != null)
            {
                var PhotoPath = HttpContext.Server.MapPath("~/Files/Stud");
                if (!Directory.Exists(PhotoPath))
                {
                    Directory.CreateDirectory(PhotoPath);
                }
                var PhotoFileName = Path.Combine(PhotoPath, model.PhotoFile.FileName);
                if (System.IO.File.Exists(PhotoFileName))
                {
                    System.IO.File.Delete(PhotoFileName);
                }
                model.PhotoFile.SaveAs(PhotoFileName);
                model.Info.Photo = model.PhotoFile.FileName;
            }
            StudentBiz.AddNew(model.Info);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int? Sn)
        {
            if (Sn != null)
            {
                StudentModel model = new StudentModel();
                model.Info = StudentBiz.GetInfo((int)Sn);
                bindEdit(model);
                return View(model);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(StudentModel model)
        {
            if (!ModelState.IsValid)
            {
                bindEdit(model);
                return View(model);
            }
            var info = StudentBiz.GetInfo(model.Info.Sn);
            info.Sn = model.Info.Sn;
            info.Name = model.Info.Name;
            info.ClassId = model.Info.ClassId;
            info.Hight = model.Info.Hight;
            info.Weight = model.Info.Weight;
            info.Birthday = model.Info.Birthday;
            if (model.PhotoFile != null)
            {
                var PhotoPath = HttpContext.Server.MapPath("~/Files/Stud");
                if (!Directory.Exists(PhotoPath))
                {
                    Directory.CreateDirectory(PhotoPath);
                }
                var PhotoFileName = Path.Combine(PhotoPath, model.PhotoFile.FileName);
                if (System.IO.File.Exists(PhotoFileName))
                {
                    System.IO.File.Delete(PhotoFileName);
                }
                model.PhotoFile.SaveAs(PhotoFileName);
                info.Photo = model.PhotoFile.FileName;
            }
            info.Memo = model.Info.Memo;
            StudentBiz.Update(info);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int Sn)
        {
            if (StudentBiz.Del(Sn))
            {
                return RedirectToAction("Index");
            }
            else
            {
                return JavaScript("alert('刪除失敗');");
            }
        }

        void bindEdit(StudentModel model)
        {
            model.ClassIdSelect = ClassMBiz.GetAll().Select(s => new SelectListItem
            {
                Value = s.Id,
                Text = s.Name
            });
        }

        void bindList(StudentListModel model)
        {
            model.ClassIdSelect = ClassMBiz.GetAll().Select(s => new SelectListItem
            {
                Value = s.Id,
                Text = s.Name
            });
        }
    }
}

WebApplication1/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Business;
using Information;
using System.IO;
using Commons;

namespace WebApplication1.Controllers
{
    public class StudentController : baseController
    {
        public ActionResult Index()
        {
            var model = new StudentListModel();
            var list = StudentBiz.QueryData(" ", " ");

            int currentPageIndex = 0;
            model.List = new MvcPaging.PagedList<StudentInfo>(list, currentPageIndex, 2);

            bindList(model);

            return View(model);
        }

        [HttpPost]
        public ActionResult Index(StudentListModel model, string sortCol, bool? sortDesc, int? page)
        {
            model.Name = string.IsNullOrWhiteSpace(model.Name) ? "" : model.Name;
            model.ClassId = string.IsNullOrWhiteSpace(model.ClassId) ? "" : model.ClassId;
            var list = StudentBiz.QueryData(model.ClassId, model.Name);

            if (!string.IsNullOrWhiteSpace(sortCol))
            {
                ListSort<StudentInfo>.GetList(list, sortCol, sortDesc.Value);
            }

            int currentPageIndex = page.HasValue ? page.Value - 1 : 0;
            int pageSize = 2;
            while (currentPageIndex > 0 &&
                list.Count <= currentPageIndex * pageSize)
            {
                currentPageIndex--;
            }

            model.List = new MvcPaging.PagedList<StudentInfo>(list, currentPageIndex, pageSize);

            return PartialView("List", model.List);
        }

        public ActionResult Create()
        {
            var model = new StudentModel();
            bindEdit(model);
            return PartialView("Edit", model);
        }

        [HttpPost]
        public ActionResult Create(StudentModel model)
        {
            if (!ModelState.IsValid)
            {
                return ReturnJson(false);
            }

            if (model.PhotoFile != null)
            {
                var PhotoPath = HttpContext.Server.MapPath("~/Files/Stud");
                if (!Directory.Exists(PhotoPath))
                {
                    Directory.CreateDirectory(PhotoPath);
                }
                var PhotoFileName = Path.Combine(PhotoPath, model.PhotoFile.FileName);
                if (System.IO.File.Exists(PhotoFileName))
                {
                    System.IO.File.Delete(PhotoFileName);
                }
                model.PhotoFile.SaveAs(PhotoFileName);
                model.Info.Photo = model.PhotoFile.FileName;
            }

            return ReturnJson(StudentBiz.AddNew(model.Info));
        }

        public ActionResult Edit(int? id)
        {
            if (id != null)
            {
                var model = new StudentModel();
                model.Info = StudentBiz.GetInfo((int)id);
                bindEdit(model);
                return PartialView(model);
            }
            return Content("error");
        }

        [HttpPost]
        public ActionResult Edit(StudentModel model)
        {
            if (!ModelState.IsValid)
            {
                return ReturnJson(false);
            }
            var info = StudentBiz.GetInfo(model.Info.Sn);
            info.Sn = model.Info.Sn;
            info.Name = model.Info.Name;
            info.ClassId = model.Info.ClassId;
            info.Hight = model.Info.Hight;
            info.Weight = model.Info.Weight;
            info.Birthday = model.Info.Birthday;
            if (model.PhotoFile != null)
            {
                var PhotoPath = HttpContext.Server.MapPath("~/Files/Stud");
                if (!Directory.Exists(PhotoPath))
                {
                    Directory.CreateDirectory(PhotoPath);
                }
                var PhotoFileName = Path.Combine(PhotoPath, model.PhotoFile.FileName);
                if (System.IO.File.Exists(PhotoFileName))
                {
                    System.IO.File.Delete(PhotoFileName);
                }
                model.PhotoFile.SaveAs(PhotoFileName);
                info.Photo = model.PhotoFile.FileName;
            }
            info.Memo = model.Info.Memo;
            return ReturnJson(StudentBiz.Update(info));
        }

        [HttpDelete]
        public ActionResult Delete(int id)
        {
            if (StudentBiz.Del(id))
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.OK);
            }
            else
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
        }

        void bindEdit(StudentModel model)
        {
            model.ClassIdSelect = ClassMBiz.GetAll().Select(s => new SelectListItem
            {
                Value = s.Id,
                Text = s.Name
            });
        }

        void bindList(StudentListModel model)
        {
            model.ClassIdSelect = ClassMBiz.GetAll().Select(s => new SelectListItem
            {
                Value = s.Id,
                Text = s.Name
            });
        }
    }
}

WebApplication1/Views/Home/Index.cshtml
@model MyTestModel

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@Html.ActionLink("model test", "Test")
<br />
@Html.ActionLink("crud + page + sort + ajax", "Index", "Student")
<br />
@Html.ActionLink("base crud + page", "Index", "StudentBase")
<br />

WebApplication1/Views/Home/Login.cshtml
@model LoginModels

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    
    <fieldset>
        <legend>後台</legend>
        <div class="editor-label">
            @Html.LabelFor(model => model.UserId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserId)
            @Html.ValidationMessageFor(model => model.UserId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Pwd)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Pwd)
            @Html.ValidationMessageFor(model => model.Pwd)
        </div>

        <p>
            <input type="submit" value="Login" />
        </p>
    </fieldset>
}

WebApplication1/Views/Home/Test.cshtml
@model MyTestModel

@{
    ViewBag.Title = "FormInput-Model";
}

<h2>FormInput-Model</h2>


@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-horizontal">
        <div class="form-group">
            @Html.DisplayNameFor(x => x.File)
            @Html.TextBoxFor(x => x.File, new { type = "file" })
            @Html.ValidationMessageFor(x => x.File)
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(x => x.Files)
            @Html.TextBoxFor(x => x.Files, new { type = "file", multiple = "multiple" })
            @Html.ValidationMessageFor(x => x.Files)
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(x => x.Id1)
            @Html.DropDownListFor(x => x.Id1, Model.Select1, "請選擇")
            @Html.ValidationMessageFor(x => x.Id1)
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(x => x.Id2) 
            @foreach (var item in Model.Select1)
            {
                @Html.RadioButtonFor(x => x.Id2, item.Value)@Html.Label(item.Text)
            }
            @Html.ValidationMessageFor(x => x.Id2)
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(x => x.List1)
            @Html.ListBoxFor(x => x.List1, Model.Select1)
            @Html.ValidationMessageFor(x => x.List1)
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(x => x.List2)
            @foreach (var s in Model.Select1)
            {
                <input type="checkbox"
                   name="@Html.IdFor(x => x.List2)"
                   value="@s.Value"
                   @{if (Model.List2 != null && Model.List2.Contains(s.Value))
                     { <text> checked='checked' </text>  }  }>
                @s.Text
            }
            @Html.ValidationMessageFor(x => x.List2)
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(x => x.ClassId)
            @Html.DisplayNameFor(x => x.StudentId)
            @Html.DropDownListFor(x => x.ClassId, Model.ClassSelect, "請選擇", new { @onchange = "CityChange(this.value)" })
            @Html.DropDownListFor(x => x.StudentId, Model.StudentSelect, "請選擇")
            @Html.ValidationMessageFor(x => x.StudentId)
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(x => x.Text1)
            @Html.TextBoxFor(x => x.Text1)
            @Html.ValidationMessageFor(x => x.Text1)
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(x => x.Text2)
            @Html.TextBoxFor(x => x.Text2)
            @Html.ValidationMessageFor(x => x.Text2)
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(x => x.Text3)
            @Html.TextBoxFor(x => x.Text3)
            @Html.ValidationMessageFor(x => x.Text3)

            @Html.DisplayNameFor(x => x.Text32)
            @Html.TextBoxFor(x => x.Text32)
            @Html.ValidationMessageFor(x => x.Text32)
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(x => x.Text4)
            @Html.TextBoxFor(x => x.Text4, "{0:yyyy-MM-dd}", new { type = "date" })
            @Html.ValidationMessageFor(x => x.Text4)
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(x => x.Text5)
            @Html.TextBoxFor(x => x.Text5)
            @Html.ValidationMessageFor(x => x.Text5)
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(x => x.Text6)
            @Html.PasswordFor(x => x.Text6)
            @Html.ValidationMessageFor(x => x.Text6)
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(x => x.Check1)
            @Html.CheckBoxFor(x => x.Check1)
            @Html.ValidationMessageFor(x => x.Check1)
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(x => x.Text6)
            @Html.HiddenFor(x => x.Text6)
            @Html.ValidationMessageFor(x => x.Text6)
        </div>
        <div class="form-group">
            <button type="submit">submit</button>
        </div>
    </div>  
}
@section Styles{
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <style>
        .custom-combobox {
            position: relative;
            display: inline-block;
        }

        .custom-combobox-toggle {
            position: absolute;
            top: 0;
            bottom: 0;
            margin-left: -1px;
            padding: 0;
        }

        .custom-combobox-input {
            margin: 0;
            padding: 5px 10px;
        }
    </style>
}

@section scripts {
    <script>
        //縣市鄉鎮
        function CityChange(city) {

            //var jsonData = JSON.stringify({
            //    'city': city
            //});

            $.ajax({
                url: "@Url.Action("ClassStud", "Home")/" + city,
                type: "GET",
                contentType: "application/json; charset=utf-8",
                //data: jsonData,
                dataType: 'json',
                success: function (result) {
                    var studSelect = $("#@Html.IdFor(x => x.StudentId)");
                    if (result) {
                        var items = "<option value=''>請選擇</option>";
                        for (var i = 0; i < result.length; i++) {
                            items += "<option value='" + result[i].Value + "'>" + result[i].Text + "</option>";
                        }
                        studSelect.html(items);
                    }
                    else {
                        alert('error');
                    }
                }
            });
            }
    </script>

    <script src="~/Scripts/jquery-ui.min.js"></script>
    <script>
        //可搜尋的TextBox
        (function ($) {
            $.widget("custom.combobox", {
                _create: function () {
                    this.wrapper = $("<span>")
                      .addClass("custom-combobox")
                      .insertAfter(this.element);

                    this.element.hide();
                    this._createAutocomplete();
                    this._createShowAllButton();
                },

                _createAutocomplete: function () {
                    var selected = this.element.children(":selected"),
                      value = selected.val() ? selected.text() : "";

                    this.input = $("<input>")
                      .appendTo(this.wrapper)
                      .val(value)
                      .attr("title", "")
                      .addClass("custom-combobox-input ui-widget ui-widget-content ui-state-default ui-corner-left")
                      .autocomplete({
                          delay: 0,
                          minLength: 0,
                          source: $.proxy(this, "_source")
                      })
                      .tooltip({
                          tooltipClass: "ui-state-highlight"
                      });

                    this._on(this.input, {
                        autocompleteselect: function (event, ui) {
                            ui.item.option.selected = true;
                            this._trigger("select", event, {
                                item: ui.item.option
                            });
                        },

                        autocompletechange: "_removeIfInvalid"
                    });
                },

                _createShowAllButton: function () {
                    var input = this.input,
                      wasOpen = false;

                    $("<a>")
                      .attr("tabIndex", -1)
                      .attr("title", "Show All Items")
                      .tooltip()
                      .appendTo(this.wrapper)
                      .button({
                          icons: {
                              primary: "ui-icon-triangle-1-s"
                          },
                          text: false
                      })
                      .removeClass("ui-corner-all")
                      .addClass("custom-combobox-toggle ui-corner-right")
                      .mousedown(function () {
                          wasOpen = input.autocomplete("widget").is(":visible");
                      })
                      .click(function () {
                          input.focus();

                          // Close if already visible
                          if (wasOpen) {
                              return;
                          }

                          // Pass empty string as value to search for, displaying all results
                          input.autocomplete("search", "");
                      });
                },

                _source: function (request, response) {
                    var matcher = new RegExp($.ui.autocomplete.escapeRegex(request.term), "i");
                    response(this.element.children("option").map(function () {
                        var text = $(this).text();
                        if (this.value && (!request.term || matcher.test(text)))
                            return {
                                label: text,
                                value: text,
                                option: this
                            };
                    }));
                },

                _removeIfInvalid: function (event, ui) {

                    // Selected an item, nothing to do
                    if (ui.item) {
                        return;
                    }

                    // Search for a match (case-insensitive)
                    var value = this.input.val(),
                      valueLowerCase = value.toLowerCase(),
                      valid = false;
                    this.element.children("option").each(function () {
                        if ($(this).text().toLowerCase() === valueLowerCase) {
                            this.selected = valid = true;
                            return false;
                        }
                    });

                    // Found a match, nothing to do
                    if (valid) {
                        return;
                    }

                    // Remove invalid value
                    this.input
                      .val("")
                      .attr("title", value + " didn't match any item")
                      .tooltip("open");
                    this.element.val("");
                    this._delay(function () {
                        this.input.tooltip("close").attr("title", "");
                    }, 2500);
                    this.input.autocomplete("instance").term = "";
                },

                _destroy: function () {
                    this.wrapper.remove();
                    this.element.show();
                }
            });
        })(jQuery);

        $(function () {
            var cb = $("#@Html.IdFor(x => x.Id1)");
            cb.combobox();
            $("#toggle").click(function () {
                cb.toggle();
            });
        });

        //IE 無法秀date
        $(function () {
            if (window.attachEvent) {
                $("input[type=date]").datepicker({ dateFormat: 'yy-mm-dd' });
            }
        });
    </script>
}